export const COMPANIES_FETCH = 'COMPANIES_FETCH';
export const COMPANIES_FETCH_ERROR = 'COMPANIES_FETCH_ERROR';
export const COMPANY_UNWATCH = 'COMPANY_UNWATCH';
export const COMPANY_WATCH = 'COMPANY_WATCH';
